@startuml

title __WEATHERAPP's Class Diagram__\n

  namespace  {
    namespace i.tuni.prog3.weatherapp {
      class fi.tuni.prog3.weatherapp.App {
      }
    }
  }
  

  namespace  {
    namespace i.tuni.prog3.weatherapp {
      class fi.tuni.prog3.weatherapp.Forecast {
      }
    }
  }
  

  namespace  {
    namespace i.tuni.prog3.weatherapp {
      class fi.tuni.prog3.weatherapp.ForecastController {
      }
    }
  }
  

  namespace  {
    namespace i.tuni.prog3.weatherapp {
      class fi.tuni.prog3.weatherapp.ForecastModel {
      }
    }
  }
  

  namespace  {
    namespace i.tuni.prog3.weatherapp {
      class fi.tuni.prog3.weatherapp.Location {
      }
    }
  }
  

  namespace  {
    namespace i.tuni.prog3.weatherapp {
      class fi.tuni.prog3.weatherapp.LocationModel {
      }
    }
  }
  

  namespace  {
    namespace i.tuni.prog3.weatherapp {
      class fi.tuni.prog3.weatherapp.MainController {
      }
    }
  }
  

  namespace  {
    namespace i.tuni.prog3.weatherapp {
      class fi.tuni.prog3.weatherapp.ReadAPI {
      }
    }
  }
  

  namespace  {
    namespace i.tuni.prog3.weatherapp {
      class fi.tuni.prog3.weatherapp.Weather {
      }
    }
  }
  

  namespace  {
    namespace i.tuni.prog3.weatherapp {
      class fi.tuni.prog3.weatherapp.WeatherController {
      }
    }
  }
  

  namespace  {
    namespace i.tuni.prog3.weatherapp {
      class fi.tuni.prog3.weatherapp.WeatherModel {
      }
    }
  }
  

  namespace  {
    namespace i.tuni.prog3.weatherapp {
      interface fi.tuni.prog3.weatherapp.iAPI {
      }
    }
  }
  

  namespace  {
    namespace i.tuni.prog3.weatherapp {
      interface fi.tuni.prog3.weatherapp.iReadAndWriteToFile {
      }
    }
  }
  

  fi.tuni.prog3.weatherapp.App -up-|> javafx.application.Application
  fi.tuni.prog3.weatherapp.ReadAPI .up.|> fi.tuni.prog3.weatherapp.iAPI


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
