@startuml

title __WEATHERAPP's Class Diagram__

class fi.tuni.prog3.weatherapp.App {
  {static} - scene : Scene
  {static} + main()
  + start()
  {static} ~ setRoot()
  {static} - loadFXML()
}

class fi.tuni.prog3.weatherapp.Forecast {
  {static} + fetchForecastData()
  {static} - convertTemp()
  {static} - weatherImage()
}

class fi.tuni.prog3.weatherapp.ForecastController {
  + dateColumn : TableColumn
  + feelsLikeColumn : TableColumn
  + hourColumn : TableColumn
  + humidityColumn : TableColumn
  + maxTempColumn : TableColumn
  + minTempColumn : TableColumn
  + tempColumn : TableColumn
  + weatherImageDailyColumn : TableColumn
  + weatherImageHourlyColumn : TableColumn
  - cityTextField : TextField
  - countryTextField : TextField
  - dailyForecastTable : TableView<ForecastModel>
  - errorLabel : Label
  - hourlyForecastTable : TableView<ForecastModel>
  - returnButton : Button
  - searchButton : Button
  - stateTextField : TextField
  + ForecastController()
  + Search()
  + clearErrorLabel()
  + returnToMain()
  - initialize()
  - updateUIDaily()
  - updateUIHourly()
}

class fi.tuni.prog3.weatherapp.ForecastModel {
  - cloudsAll : double
  - dt : int
  - dtTxt : String
  - feelsLike : double
  - humidity : double
  - pressure : double
  - sysPod : String
  - tempMax : double
  - tempMin : double
  - temperature : double
  - weatherDescription : String
  - weatherIcon : String
  - weatherId : int
  - weatherImage : ImageView
  - weatherMain : String
  - windSpeed : double
  + ForecastModel()
  + getCloudsAll()
  + getDt()
  + getDtTxt()
  + getFeelsLike()
  + getHumidity()
  + getIconCode()
  + getMaxTemperature()
  + getMinTemperature()
  + getPressure()
  + getSysPod()
  + getTemperature()
  + getWeatherDescription()
  + getWeatherId()
  + getWeatherImage()
  + getWeatherMain()
  + getWindSpeed()
  + setCloudsAll()
  + setDt()
  + setDtTxt()
  + setFeelsLike()
  + setHumidity()
  + setMaxTemperature()
  + setMinTemperature()
  + setPressure()
  + setSysPod()
  + setTemperature()
  + setWeatherDescription()
  + setWeatherIcon()
  + setWeatherId()
  + setWeatherMain()
  + setWindSpeed()
}

class fi.tuni.prog3.weatherapp.Location {
  {static} + fetchLocationData()
}

class fi.tuni.prog3.weatherapp.LocationModel {
  - country : String
  - lat : double
  - lon : double
  - name : String
  + LocationModel()
  + getCountry()
  + getLatitude()
  + getLongitude()
  + getName()
  + setCountry()
  + setLatitude()
  + setLongtitude()
  + setName()
}

class fi.tuni.prog3.weatherapp.MainController {
  - mainForecastButton : Button
  - mainQuitButton : Button
  - mainVBox : VBox
  - mainWeatherButton : Button
  - maininformationLabel : Label
  - maintitleLabel : Label
  - Quit()
  - SwitchToForecast()
  - SwitchToWeather()
}

class fi.tuni.prog3.weatherapp.ReadAPI {
  {static} - API_KEY : String
  {static} + createHttpRequest()
  + getCurrentWeather()
  + getForecast()
  + lookUpLocation()
}

class fi.tuni.prog3.weatherapp.Weather {
  {static} + fetchWeatherData()
}

class fi.tuni.prog3.weatherapp.WeatherController {
  - cityTextField : TextField
  - countryTextField : TextField
  - errorLabel : Label
  - feels_likeLabel : Label
  - humidityLabel : Label
  - pressureLabel : Label
  - rain_intensityLabel : Label
  - searchButton : Button
  - stateTextField : TextField
  - tempLabel : Label
  - temp_maxLabel : Label
  - temp_minLabel : Label
  - titleLabel : Label
  - weatherImage : ImageView
  - weather_descriptionLabel : Label
  - wind_speedLabel : Label
  + Search()
  + clearErrorLabel()
  + returnToMain()
  - updateUI()
}

class fi.tuni.prog3.weatherapp.WeatherModel {
  - feels_like : double
  - humidity : double
  - iconCode : String
  - pressure : double
  - rain_intensity : double
  - temp : double
  - temp_max : double
  - temp_min : double
  - weather_description : String
  - wind_speed : double
  + WeatherModel()
  + getFeelsLike()
  + getHumidity()
  + getIconCode()
  + getMaxTemperature()
  + getMinTemperature()
  + getPressure()
  + getRainIntensity()
  + getTemperature()
  + getWeatherDescription()
  + getWindSpeed()
  + setFeelsLike()
  + setHumidity()
  + setIconCode()
  + setMaxTemperature()
  + setMinTemperature()
  + setPressure()
  + setRainIntensity()
  + setTemperature()
  + setWeatherDescription()
  + setWindSpeed()
}

interface fi.tuni.prog3.weatherapp.iAPI {
  {abstract} + getCurrentWeather()
  {abstract} + getForecast()
  {abstract} + lookUpLocation()
}

interface fi.tuni.prog3.weatherapp.iReadAndWriteToFile {
  {abstract} + readFromFile()
  {abstract} + writeToFile()
}

fi.tuni.prog3.weatherapp.App -up-|> javafx.application.Application
fi.tuni.prog3.weatherapp.ReadAPI .up.|> fi.tuni.prog3.weatherapp.iAPI

right footer

PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml

